#
#[theme]
#primaryColor = "#F63366"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#F0F2F6"
#textColor = "#262730"

[server]
port = 3530
maxUploadSize = 500
headless = true

#[layout]
## Change layout to wide
#wideMode = true
